import { createSlice } from "@reduxjs/toolkit";

const locationSlice = createSlice({
    name: "locations",
    initialState: {
        locations: [
            {
                id: "123jn123",
                name: "Australia",
                work_week: [("Wednesday", "Saturday")],
                quota_reset: "User Employment Date",
                year_start_month: "March",
                year_start_date: 4,
                expiry_date: false,
                default: true,
                week_starts_on: "Sunday",
                time_zone: "GMT+01:00 Europe/Belgrade",
                users: [
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                ],
            },
            {
                id: "123ddfsf234",
                name: "Belarus",
                work_week: [("Wednesday", "Saturday")],
                quota_reset: "User Employment Date",
                year_start_month: "March",
                year_start_date: 4,
                expiry_date: false,
                default: false,
                week_starts_on: "Sunday",
                time_zone: "GMT+01:00 Europe/Belgrade",
                users: [
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                ],
            },
            {
                id: "123dfsf234",
                name: "Belarus",
                work_week: [("Wednesday", "Saturday")],
                quota_reset: "User Employment Date",
                year_start_month: "March",
                year_start_date: 4,
                expiry_date: false,
                default: false,
                week_starts_on: "Sunday",
                time_zone: "GMT+01:00 Europe/Belgrade",
                users: [
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                    "Warwick Davis",
                ],
            },
        ],
    },
    reducers: {
        addLocation(state, action) {
            state.locations.push({
                id: new Date().toISOString(),
                name: action.payload.location.name,
                work_week: action.payload.location.work_week,
                quota_reset: action.payload.location.quota_reset,
                year_start_month: action.payload.location.year_start_month,
                year_start_date: action.payload.location.year_start_date,
                expiry_date: action.payload.location.expiry_date,
                default: action.payload.location.default,
                week_starts_on: action.payload.location.week_starts_on,
                time_zone: action.payload.location.time_zone,
                users: action.payload.location.users,
            });
        },
        removeLocation(state, action) {
            state.locations = state.locations.filter(
                (location) => location.id !== action.payload.id
            );
        },
    },
});

export const { addLocation, removeLocation } = locationSlice.actions;

export default locationSlice.reducer;
